namespace APThermo.Protocol.Tests;

/// <summary>
/// The tree-contract signature snapshot (root <c>BOOT.md</c>, the guards audit's F9): a second snapshot, alongside the
/// public surface's, over every internal type named under a ✅ tree-contract heading of any node's <c>API.md</c>.
/// <c>DeclarationTests</c> checks only that a named type and member exist, not that a member's own signature is the one
/// the document promises; this level pins the signature the way <c>SurfaceTests</c> pins the public surface, so
/// renaming a parameter or widening a type of an internal, tree-contract-only member moves this file in the same diff
/// a reviewer already watches for <c>PublicSurface.approved.txt</c>.
/// </summary>
public sealed class TreeContractSnapshotTests
{
    /// <summary>The path of the approved tree-contract snapshot.</summary>
    public static string ApprovedPath => Path.Combine(Tree.Root, "tests", "Protocol.Tests", "TreeContract.approved.txt");

    /// <summary>The path the actual tree-contract signatures are written to on a mismatch, so a reviewer can diff it
    /// against the approved snapshot; deleted again when the two agree.</summary>
    public static string ActualPath => Path.Combine(Tree.Root, "tests", "Protocol.Tests", "TreeContract.actual.txt");

    /// <summary>Every internal type named under a tree-contract heading of any node's API.md matches the approved
    /// snapshot.</summary>
    [Fact]
    public void TheTreeContractSignaturesMatchTheApprovedSnapshot()
    {
        var groups = TreeContractGroups().ToList();
        Assert.NotEmpty(groups);
        var actual = SurfaceTests.DescribeTypes(
            "# Tree-contract signatures: every internal type named under a tree-contract heading of any node's API.md.",
            "# Generated by Protocol.Tests.TreeContractSnapshotTests; a tripwire, not a contract: the contract is the API.md of each node.",
            "# On an intended change, update that API.md and replace this file with TreeContract.actual.txt in the same commit.",
            groups.Select(group => (group.Node.Name, (IEnumerable<Type>)group.Types)), MemberAccessibility.IsPublicOrInternal);
        Compare(actual);
    }

    private static void Compare(string actual)
    {
        if (!File.Exists(ApprovedPath))
        {
            File.WriteAllText(ApprovedPath, actual);
            Assert.Fail($"No approved snapshot of the tree-contract signatures existed, so one was written to {ApprovedPath}. " +
                        "Read it, satisfy yourself that it is the tree contract every API.md describes, commit it, and re-run.");
        }

        var approved = SurfaceTests.Normalise(File.ReadAllText(ApprovedPath));
        var current = SurfaceTests.Normalise(actual);
        if (approved == current)
        {
            File.Delete(ActualPath);
            return;
        }

        Fail(actual, approved, current);
    }

    private static void Fail(string actual, string approved, string current)
    {
        File.WriteAllText(ActualPath, actual);
        var approvedLines = approved.Split('\n');
        var currentLines = current.Split('\n');
        var first = Enumerable.Range(0, Math.Max(approvedLines.Length, currentLines.Length))
            .First(i => i >= approvedLines.Length || i >= currentLines.Length || approvedLines[i] != currentLines[i]);
        Assert.Fail(
            "The tree-contract signatures no longer match TreeContract.approved.txt.\n" +
            $"First difference at line {first + 1}: approved '{(first < approvedLines.Length ? approvedLines[first] : "<end>")}', " +
            $"actual '{(first < currentLines.Length ? currentLines[first] : "<end>")}'.\n" +
            $"What it is now was written to {ActualPath}. If the change is intended, update the API.md of the node that owns the type " +
            "first, then replace the approved file with the actual one in the same commit.");
    }

    /// <summary>Every node of the tree, with the types of its own <c>API.md</c> that a ✅ tree-contract heading names,
    /// ordinal by full name; a node that names none contributes no section, so the snapshot stays as small as the
    /// contract it pins.</summary>
    private static IEnumerable<(Node Node, List<Type> Types)> TreeContractGroups() =>
        Tree.Nodes.OrderBy(node => node.RelativePath, StringComparer.Ordinal)
            .Select(node => (node, TreeContractTypesOf(node)))
            .Where(pair => pair.Item2.Count > 0);

    private static List<Type> TreeContractTypesOf(Node node)
    {
        var names = ApiDeclarations.DeclaredTypeSections(File.ReadAllText(node.Api))
            .Where(pair => pair.TreeContract).Select(pair => pair.Name).ToHashSet();
        return names.Count == 0
            ? []
            : [.. NodeAssemblies.TypesOf(node).Where(type => names.Contains(TypeShape.SimpleName(type)))
                .OrderBy(type => type.FullName, StringComparer.Ordinal)];
    }
}
