// Generated by tests/Thermo.Tests/Elementary/generate_tables.py (mpmath 1.3.0, 300 bits). Do not edit by hand.
namespace APThermo.Thermo.Elementary;

/// <summary>The constants of the elementary functions, each an exact real rounded to binary64 by the generator.</summary>
internal static class ElementaryConstants
{
    /// <summary>64/ln 2, the reduction's multiplier.</summary>
    public const double ExpInverseStep = 92.33248261689366;

    /// <summary>RN(ln 2/64), the reduction's high step.</summary>
    public const double ExpStepHigh = 0.010830424696249145;

    /// <summary>ln 2/64 − ExpStepHigh, rounded.</summary>
    public const double ExpStepLow = 3.623510646634843e-19;

    /// <summary>ln 2, high part of the double-double.</summary>
    public const double Ln2High = 0.6931471805599453;

    /// <summary>ln 2, low part of the double-double.</summary>
    public const double Ln2Low = 2.3190468138462996e-17;

    /// <summary>ln 2, first term of the triple-double.</summary>
    public const double Ln2T0 = 0.6931471805599453;

    /// <summary>ln 2, second term of the triple-double.</summary>
    public const double Ln2T1 = 2.3190468138462996e-17;

    /// <summary>ln 2, third term of the triple-double.</summary>
    public const double Ln2T2 = 5.707708438416212e-34;

    /// <summary>1/ln 2.</summary>
    public const double InverseLn2 = 1.4426950408889634;

    /// <summary>1/3, high part of the double-double.</summary>
    public const double ThirdHigh = 0.3333333333333333;

    /// <summary>1/3, low part of the double-double.</summary>
    public const double ThirdLow = 1.850371707708594e-17;
}
