"""Generates the oracle fixtures of tests/Thermo.Tests/Elementary/fixtures.

Usage: python generate_fixtures.py --wc-dir <directory holding exp.wc, log.wc, pow.wc and LICENSE of CORE-MATH>

Writes, per function f in exp, log, pow:
  fixtures/f.txt         the constructed families: bit patterns of the inputs and of the correctly rounded result;
  fixtures/f.wc.txt      the selection of CORE-MATH's worst-case list, same line form;
  fixtures/f.margin.txt  inputs of the fast-path margin fact with the exact value as a double-double (hi, lo).
and fixtures/PROVENANCE.txt. Every result is the exact value (mpmath, 400 bits) rounded to nearest, ties to even.

The selection of a worst-case list (rule recorded in PROVENANCE.txt): every input of the list that is finite, positive
for exp's argument-free domain of log and, for pow, either positive or with an integer exponent, is scored by the
distance of its exact result from the midpoint of the two neighbouring doubles; the HARDEST (smallest nonzero distance), a uniform
sample of the exact MIDPOINTS (distance 0) and a uniform deterministic SAMPLE (every n-th input in file order) are kept.
"""
import argparse
import hashlib
import multiprocessing
import os
import sys

import mpmath

import oracle

HARDEST = 3000
MIDPOINTS = 1000
SAMPLE = 4000
FUNCTIONS = ("exp", "log", "pow")


def write_lines(path, header, lines):
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(header + lines) + "\n")
    print("wrote", path, len(lines), "lines")


def families(func):
    return {"exp": oracle.exp_inputs, "log": oracle.log_inputs, "pow": oracle.pow_inputs}[func]()


def margin_inputs(func):
    return {"exp": oracle.exp_margin_inputs, "log": oracle.log_margin_inputs, "pow": oracle.pow_margin_inputs}[func]()


def result_line(func, args):
    return " ".join(oracle.hexs(a) for a in args) + " " + oracle.hexs(oracle.oracle(func, args))


def margin_line(func, args):
    value = oracle.exact(func, args)
    high = float(value)
    low = float(value - mpmath.mpf(high))
    return " ".join(oracle.hexs(a) for a in args) + " " + oracle.hexs(high) + " " + oracle.hexs(low)


def score(job):
    func, args = job
    value = oracle.exact(func, args)
    return float(oracle.midpoint_distance(value)) if value is not None else 1.0


def select(func, wc_dir, workers):
    entries = oracle.wc_entries(os.path.join(wc_dir, func + ".wc"), func)
    with multiprocessing.Pool(workers) as pool:
        scores = pool.map(score, [(func, e) for e in entries], chunksize=2000)
    order = sorted(range(len(entries)), key=lambda i: (scores[i], i))
    midpoints = [i for i in order if scores[i] == 0.0]
    nonexact = [i for i in order if scores[i] != 0.0]
    chosen = set(nonexact[:HARDEST])
    chosen.update(midpoints[:: max(1, len(midpoints) // MIDPOINTS)])
    step = max(1, len(entries) // SAMPLE)
    chosen.update(range(0, len(entries), step))
    kept = sorted(chosen)
    print(func, "list", len(entries), "kept", len(kept), "exact midpoints", len(midpoints), "hardest nonzero distance",
          scores[nonexact[0]], "cut at", scores[nonexact[HARDEST - 1]])
    return len(entries), kept, [entries[i] for i in kept]


def sha256(path):
    with open(path, "rb") as handle:
        return hashlib.sha256(handle.read()).hexdigest()


def provenance(wc_dir, totals):
    with open(os.path.join(wc_dir, "LICENSE"), encoding="utf-8") as handle:
        licence = handle.read().strip()
    lines = [
        "Provenance of the elementary-function fixtures",
        "",
        "f.txt and f.margin.txt (f = exp, log, pow) are generated by generate_fixtures.py from the families of oracle.py;",
        "every result is the exact value computed by mpmath %s at 400 bits, rounded to nearest, ties to even." % mpmath.__version__,
        "",
        "f.wc.txt selects inputs from the published worst-case lists of the CORE-MATH project:",
        "  source:   https://gitlab.inria.fr/core-math/core-math, src/binary64/{exp,log,pow}/{exp,log,pow}.wc",
        "  commit:   284b3b0e198042c38f5c30316f696786b10816b0",
        "  licence:  MIT (text below); the lists are not committed whole (the files are 25 MB, 3 MB and 32 MB);",
        "            the inputs listed here are a selection, and the results are computed by the oracle above.",
        "  sha256 of the lists read: " + ", ".join("%s.wc %s" % (f, sha256(os.path.join(wc_dir, f + ".wc"))) for f in FUNCTIONS),
        "  selection rule: of the inputs of a list that are finite and in the oracle's domain (exp: -746 <= x <= 710; log: x > 0;",
        "    pow: x != 0, y != 0, and x > 0 or y an integer) every input is scored by the distance of its exact result from the",
        "    midpoint of the two neighbouring doubles, in ulps (0 at an exact midpoint, 0.25 on average for a random input;",
        "    smaller is harder). Kept, in file order: the %d hardest inputs of nonzero distance (ties by file order); every n-th" % HARDEST,
        "    input of those at distance 0 (exact midpoints, which pow's list holds by the thousand), n = floor(count / %d); and" % MIDPOINTS,
        "    every n-th input of the whole list, n = floor(list length / %d)." % SAMPLE,
        "  usable inputs per list (before the selection): " + ", ".join("%s %d" % (f, totals[f]) for f in FUNCTIONS),
        "  The full lists are read by the one optional fact LongRunning TheFullWorstCaseListsAreCorrectlyRounded when the",
        "  environment variable APTHERMO_COREMATH_WC names a directory holding them.",
        "",
        "CORE-MATH licence text:",
        "",
        licence,
    ]
    return lines


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--wc-dir", required=True)
    parser.add_argument("--workers", type=int, default=6)
    options = parser.parse_args()
    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, "fixtures")
    os.makedirs(out, exist_ok=True)
    version = "mpmath %s, 400 bits, correct rounding to nearest even" % mpmath.__version__
    totals = {}
    for func in FUNCTIONS:
        columns = "x y result" if func == "pow" else "x result"
        header = ["# %s: bit patterns (16 hex digits), columns: %s; oracle: %s" % (func, columns, version),
                  "# the constructed families of oracle.py (generate_fixtures.py)"]
        write_lines(os.path.join(out, func + ".txt"), header, [result_line(func, a) for a in families(func)])
        columns = "x y hi lo" if func == "pow" else "x hi lo"
        header = ["# %s fast-path margin inputs: bit patterns, columns: %s; hi + lo is the exact value (double-double) of %s" %
                  (func, columns, "x^y" if func == "pow" else func + "(x)")]
        write_lines(os.path.join(out, func + ".margin.txt"), header, [margin_line(func, a) for a in margin_inputs(func)])
        total, kept, entries = select(func, options.wc_dir, options.workers)
        totals[func] = total
        columns = "x y result" if func == "pow" else "x result"
        header = ["# %s worst cases selected from CORE-MATH (see PROVENANCE.txt); columns: %s; oracle: %s" % (func, columns, version)]
        write_lines(os.path.join(out, func + ".wc.txt"), header, [result_line(func, a) for a in entries])
    with open(os.path.join(out, "PROVENANCE.txt"), "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(provenance(options.wc_dir, totals)) + "\n")


if __name__ == "__main__":
    sys.exit(main())
