"""Generates the constant tables of src/Thermo/Elementary: ExpTable.cs, LogTable.cs and ElementaryConstants.cs.

Every value is an exact real (mpmath, 300 bits) rounded to binary64 by float(); a double-double is the rounded
value and the rounded remainder, a triple-double adds the next remainder. Nothing is typed by hand: the generated
files carry the header below and a fact of tests/Thermo.Tests/Elementary checks their identities.

Usage: python generate_tables.py [output-directory]   (default: src/Thermo/Elementary of this repository)
"""
import os
import sys

import mpmath

mpmath.mp.prec = 300

HEADER = ("// Generated by tests/Thermo.Tests/Elementary/generate_tables.py (mpmath {version}, 300 bits). "
          "Do not edit by hand.\n").format(version=mpmath.__version__)


def double_double(v):
    high = float(v)
    return high, float(v - mpmath.mpf(high))


def triple_double(v):
    high = float(v)
    rest = v - mpmath.mpf(high)
    middle = float(rest)
    return high, middle, float(rest - mpmath.mpf(middle))


def literal(v):
    return "0.0" if v == 0 else repr(v)


def exp_table():
    lines = [HEADER.rstrip("\n"), "namespace APThermo.Thermo.Elementary;", ""]
    lines.append("/// <summary>2^(j/64) as a double-double for j = 0 … 63: the exp fast path's table, switches over constants "
                 "(no static state).</summary>")
    lines.append("internal static class ExpTable")
    lines.append("{")
    lines.append("    /// <summary>2^(j/64) as a double-double, <paramref name=\"j\"/> in 0 … 63.</summary>")
    lines.append("    public static Dd At(int j) => j < 32 ? Low(j) : High(j);")
    for name, start in (("Low", 0), ("High", 32)):
        lines.append("")
        lines.append("    private static Dd %s(int j) => j switch" % name)
        lines.append("    {")
        for j in range(start, start + 32):
            high, low = double_double(mpmath.power(2, mpmath.mpf(j) / 64))
            lines.append("        %d => new Dd(%s, %s)," % (j, literal(high), literal(low)))
        lines.append("        _ => new Dd(0.0, 0.0),")
        lines.append("    };")
    lines.append("}")
    return "\n".join(lines) + "\n"


def log_table():
    lines = [HEADER.rstrip("\n"), "namespace APThermo.Thermo.Elementary;", ""]
    lines.append("/// <summary>c_i = RN(1/(1 + i/32)) (c_0 = 1, c_32 = 1/2) and −log c_i as a double-double for i = 0 … 32: the log "
                 "fast path's table, a switch over constants (no static state). The entry for i = 32 is the ln 2 double-double "
                 "itself, so that e ln 2 − log c cancels to exactly 0 for the arguments just below 1.</summary>")
    lines.append("internal static class LogTable")
    lines.append("{")
    lines.append("    /// <summary>The entry of <paramref name=\"i\"/> in 0 … 32.</summary>")
    lines.append("    public static LogTableEntry At(int i) => i switch")
    lines.append("    {")
    ln2 = double_double(mpmath.log(2))
    for i in range(33):
        if i == 0:
            c = 1.0
        elif i == 32:
            c = 0.5
        else:
            c = float(1 / (1 + mpmath.mpf(i) / 32))
        high, low = ln2 if i == 32 else double_double(-mpmath.log(mpmath.mpf(c)))
        lines.append("        %d => new LogTableEntry(%s, %s, %s)," % (i, literal(c), literal(high), literal(low)))
    lines.append("        _ => new LogTableEntry(0.0, 0.0, 0.0),")
    lines.append("    };")
    lines.append("}")
    return "\n".join(lines) + "\n"


def constants():
    ln2 = mpmath.log(2)
    step = ln2 / 64
    step_high = float(step)
    values = [
        ("ExpInverseStep", "64/ln 2, the reduction's multiplier", float(64 / ln2)),
        ("ExpStepHigh", "RN(ln 2/64), the reduction's high step", step_high),
        ("ExpStepLow", "ln 2/64 − ExpStepHigh, rounded", float(step - mpmath.mpf(step_high))),
        ("Ln2High", "ln 2, high part of the double-double", double_double(ln2)[0]),
        ("Ln2Low", "ln 2, low part of the double-double", double_double(ln2)[1]),
    ]
    t0, t1, t2 = triple_double(ln2)
    values += [
        ("Ln2T0", "ln 2, first term of the triple-double", t0),
        ("Ln2T1", "ln 2, second term of the triple-double", t1),
        ("Ln2T2", "ln 2, third term of the triple-double", t2),
        ("InverseLn2", "1/ln 2", float(1 / ln2)),
    ]
    third = double_double(1 / mpmath.mpf(3))
    values += [
        ("ThirdHigh", "1/3, high part of the double-double", third[0]),
        ("ThirdLow", "1/3, low part of the double-double", third[1]),
    ]
    lines = [HEADER.rstrip("\n"), "namespace APThermo.Thermo.Elementary;", ""]
    lines.append("/// <summary>The constants of the elementary functions, each an exact real rounded to binary64 by the generator.</summary>")
    lines.append("internal static class ElementaryConstants")
    lines.append("{")
    for index, (name, summary, value) in enumerate(values):
        if index:
            lines.append("")
        lines.append("    /// <summary>%s.</summary>" % summary)
        lines.append("    public const double %s = %s;" % (name, literal(value)))
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.normpath(os.path.join(here, "..", "..", "..", "src", "Thermo", "Elementary"))
    os.makedirs(out, exist_ok=True)
    for name, text in (("ExpTable.cs", exp_table()), ("LogTable.cs", log_table()), ("ElementaryConstants.cs", constants())):
        with open(os.path.join(out, name), "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)
        print("wrote", os.path.join(out, name))


if __name__ == "__main__":
    main()
